// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IndexFiles():Promise<string>;

export function SearchFiles(arg1:string):Promise<Array<string>>;
