// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IndexFiles() {
  return window['go']['backend']['App']['IndexFiles']();
}

export function SearchFiles(arg1) {
  return window['go']['backend']['App']['SearchFiles'](arg1);
}
